# Inspired by https://github.com/Energy-Sparks/energy-sparks/blob/master/.github/actions/setup/action.yml
name: Setup
description: Set up Manyfold build environment
runs:
  using: composite
  steps:
    - name: Install system requirements
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: assimp-utils
    - name: Set up Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: yarn
    - name: Install yarn packages
      run: yarn install
      shell: bash
