require:
  - standard
  - rubocop-pundit

plugins:
  - rubocop-performance
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-i18n
  - rubocop-factory_bot

inherit_gem:
  standard: config/base.yml
  rswag-specs: .rubocop_rspec_alias_config.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/bundle
    - bin/yarn
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - ".git/**/*"

I18n/GetText:
  Enabled: false
I18n/RailsI18n:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "app/lib/cli/**/*"
Rails/Output:
  Exclude:
    - "app/lib/cli/**/*"
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/requests/api/**/*"
RSpec/NoExpectationExample:
  Exclude:
    - spec/system/documentation_screenshots_spec.rb
Style/ItAssignment:
  Enabled: false
