---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/.well-known/nodeinfo":
    get:
      summary: Get nodeinfo URL
      tags:
      - Nodeinfo
      responses:
        '200':
          description: blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                required:
                - links
  "/nodeinfo/2.0":
    get:
      summary: Get nodeinfo
      tags:
      - Nodeinfo
      responses:
        '200':
          description: node info
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                  protocols:
                    type: array
                  services:
                    type: object
                  openRegistrations:
                    type: coolean
                required:
                - version
                - protocols
                - services
                - openRegistrations
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
