---
:concurrency: <%= ENV.fetch("DEFAULT_WORKER_CONCURRENCY", 4) %>
:queues:
  - critical
  - high
  - scan
  - default
  - low
  # legacy queues kept for a while for upgrade compatibility
  - analysis
  - activity
  - upgrade
