name: Image smoke test

on:
  workflow_run:
    workflows: [Docker]
    types:
      - completed
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Work out Docker tags
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/manyfold-solo
          tags: |
            type=ref,event=pr
      - name: Smoke test
        run: curl http://localhost:3214/health --fail-with-body
    services:
      manyfold:
        image: ${{ steps.docker_meta.outputs.tags }}
        env:
          SECRET_KEY_BASE: abc123
        options: >-
          --health-cmd "curl http://localhost:3214/health --fail-with-body"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3214:3214
