name: Image smoke test

on:
  workflow_run:
    workflows: [Docker]
    types:
      - completed
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Smoke test
        run: curl http://localhost:3214/health --fail-with-body
    services:
      manyfold:
        image: ghcr.io/${{ github.repository_owner }}/manyfold-solo:sha-${{ github.sha }}
        env:
          SECRET_KEY_BASE: abc123
        options: >-
          --health-cmd "cat tmp/pids/server.pid"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 6
        ports:
          - 3214:3214
